// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3NY-oK2NreYOF5k2SLFSacPJj-tqwsOA',
    appId: '1:987978740915:web:8228e82a9cf26064a2acc6',
    messagingSenderId: '987978740915',
    projectId: 'shopsmart-343cb',
    authDomain: 'shopsmart-343cb.firebaseapp.com',
    storageBucket: 'shopsmart-343cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGmbXCDAmKrohVuUrdKiW58F821DzC_dc',
    appId: '1:987978740915:android:bd6c8781d28725afa2acc6',
    messagingSenderId: '987978740915',
    projectId: 'shopsmart-343cb',
    storageBucket: 'shopsmart-343cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrVt7SKhJCTA2tzegMAdeTALR1-fIKDxQ',
    appId: '1:987978740915:ios:ddfa1aeb3864fc23a2acc6',
    messagingSenderId: '987978740915',
    projectId: 'shopsmart-343cb',
    storageBucket: 'shopsmart-343cb.appspot.com',
    iosBundleId: 'com.example.shopsmartAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrVt7SKhJCTA2tzegMAdeTALR1-fIKDxQ',
    appId: '1:987978740915:ios:2c31b77b8425ccd1a2acc6',
    messagingSenderId: '987978740915',
    projectId: 'shopsmart-343cb',
    storageBucket: 'shopsmart-343cb.appspot.com',
    iosBundleId: 'com.example.shopsmartAdmin.RunnerTests',
  );
}
